[package]
name = "archetype"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Lightweight golden testing library."

[dependencies]
paste = "1.0.14"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
similar = "2.3.0"
