[package]
name = "archetype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.14"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
similar = "2.3.0"
